universe = container
container_image = ./astro-pytorch.sif

shell = ./run_train_sweep.sh $(run_name) $(epochs) $(image_size) $(n_levels) $(n_steps) $(samples) $(lr) $(cond_dim) $(batch_size)

log    = logs/$(run_name)_$(Cluster)_$(Process).log
output = logs/$(run_name)_$(Cluster)_$(Process).out
error  = logs/$(run_name)_$(Cluster)_$(Process).err

transfer_input_files = run_train_sweep.sh, train.py, models/llm_encoder.py, models/flow_model.py, Data/apod_preloaded_dataset.csv, Data/dataset.py, astro-pytorch.sif

transfer_output_files = checkpoints

request_gpus   = 1
request_cpus   = 4
request_memory = 32GB
request_disk   = 30GB

requirements = (OpSysMajorVer == 8 || OpSysMajorVer == 9)

queue run_name, epochs, image_size, n_levels, n_steps, samples, lr, cond_dim, batch_size from (
    config1,  50, 224, 3, 4, 6000, 1e-5,  256, 16
    config2,  80, 224, 3, 5, 8000, 1e-5, 1024,  4
)
